[project]
name = "agno_tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agno>=0.1.0",
    "duckduckgo-search>=7.3.2",
    "openai>=1.63.0",
    "yfinance>=0.2.53",
]
